defaults:
  - model: rtdetrv2_50
  - _self_

effective_batch_size: 64
step_batch_size : 4
epochs: 30
lr: 1e-4
weight_decay: 1e-4
warmup_epochs: 5
root_dir: Fruit_dataset
data_conf_file : data.yaml
log : True
seed : 42
n_images : 6
patience : 15
delta : 0.001
num_workers : 4
lr_back_factor : 10
lr_neck_factor : 5
wait : False
info : False
min_area : 4.0
aug : hard
do_sample : False
freeze_backbone : False
partially_freeze_backbone : False
upload : False
optim : 8bit
threshold : 0.001

mosaic:
  use : False
  prob : 0.0
  disable_epoch : 15

phase : 1
eta_min_factor : 25
lin_start_factor : 0.001

ema:
  use : True
  decay : 0.9999

ckpt:
  save : False
  load:
    model_only : False
    all : False

smart_optim : False
fp16 : True
